baseURL = 'https://youngerfill.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'geekdoc'
publishDir = 'docs'

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

[taxonomies]
   tag = "tags"
