baseURL = 'https://youngerfill.github.io/hugonotes/'
languageCode = 'en-us'
title = 'hugonotes'
theme = 'geekdoc'
publishDir = 'docs'

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

[taxonomies]
   tag = "tags"

[params]
# (Optional, default static/brand.svg) Set the path to a logo for the Geekdoc
# relative to your 'static/' folder.
  geekdocLogo = "alpha_1px.png"
